table Avg_daily
	lineageTag: 9ad7ebb9-cf1c-446c-beb7-7e71b37135e4

	column Material_Plant_Key
		dataType: string
		lineageTag: aea38353-41ac-4002-beca-e83ed40218a1
		summarizeBy: none
		sourceColumn: Material_Plant_Key

		annotation SummarizationSetBy = Automatic

	column Avg_Daily_Sales_for_last_6_weeks
		dataType: double
		lineageTag: 27064b9c-34d0-42df-976f-b9b00c699e64
		summarizeBy: sum
		sourceColumn: Avg_Daily_Sales_for_last_6_weeks

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Avg_Fcst_by_Day_for_next_6_weeks
		dataType: double
		lineageTag: dcc586b2-6238-493a-9d27-e7934fdfe993
		summarizeBy: sum
		sourceColumn: Avg_Fcst_by_Day_for_next_6_weeks

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Snapshot_Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: ad119a0e-5df7-496b-832d-f10d7d7e0106
		summarizeBy: none
		sourceColumn: Snapshot_Date

		variation Variación
			isDefault
			relationship: 19ff6f6d-d529-441c-ab5b-a5115fac1761
			defaultHierarchy: LocalDateTable_2c2d6ff7-66cb-4e6f-990f-a22d3076cf8e.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Material_Key
		dataType: string
		lineageTag: 1d93c23f-58bc-4685-83e2-1ca7000011c9
		summarizeBy: none
		sourceColumn: Material_Key

		annotation SummarizationSetBy = Automatic

	partition Avg_daily = m
		mode: import
		source =
				let
				    Origen = Sql.Database("a7niicbdnafeziyn7pkezid2ei-xvfrvotyhelefgem6tjbs5rb4q.datawarehouse.fabric.microsoft.com", "LH_Integrated_Business_Planning_Unstructured_Flows"),
				    Bronze_is_src_avg_daily = Origen{[Schema="Bronze",Item="is_src_avg_daily"]}[Data],
				
				    ConNombre   = Table.AddColumn(Bronze_is_src_avg_daily, "FileName", each Text.AfterDelimiter([FilePath], "/", {0, RelativePosition.FromEnd}), type text),
				    ConSnapshot = Table.AddColumn(ConNombre, "Snapshot_Date", each try Date.FromText(Text.Start([FileName], 10), [Format="yyyy-MM-dd", Culture="en-US"]) otherwise null, type date),
				
				    UltimoSnap  = List.Max(ConSnapshot[Snapshot_Date]),
				    // si no parsea fecha (todo null), NO filtra — así nunca te deja tabla vacía
				    SoloUltimo  = if UltimoSnap = null then ConSnapshot else Table.SelectRows(ConSnapshot, each [Snapshot_Date] = UltimoSnap),
				
				    Renombrada  = Table.RenameColumns(SoloUltimo, {{"Material", "Material_Plant_Key"}}),
				    ConMatKey   = Table.AddColumn(Renombrada, "Material_Key", each Text.BeforeDelimiter([Material_Plant_Key], "-", {0, RelativePosition.FromEnd}), type text),
				
				    Tipos = Table.TransformColumnTypes(ConMatKey, {
				        {"Avg_Daily_Sales_for_last_6_weeks", type number},
				        {"Avg_Fcst_by_Day_for_next_6_weeks", type number}
				    }),
				    Final = Table.RemoveColumns(Tipos, {"FilePath", "FileName"})
				in
				    Final

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

