table 'Demand Basis'
	lineageTag: a6811e29-ea97-4a51-85c6-359f797ed096

	column Basis
		dataType: string
		lineageTag: 9fb31622-f903-4d7c-8539-c7104b07a9de
		summarizeBy: none
		sourceColumn: Basis
		sortByColumn: Orden

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Orden
		dataType: int64
		formatString: 0
		lineageTag: 0bd62753-866a-4795-bc71-f6f08508687d
		summarizeBy: sum
		sourceColumn: Orden

		annotation SummarizationSetBy = Automatic

	partition 'Demand Basis' = m
		mode: import
		source =
				let
				    Origen = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WCijKz0pNLsnMz1PSUTJQitWJVnLLL0pNTiwuAQoYggWCE3NSi4E8I6XYWAA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Basis = _t, Orden = _t]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"Basis", type text}, {"Orden", Int64.Type}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

